In [4]:
from datascience import *
import numpy as np
# import glob
import pandas as pd
% matplotlib inline

### A little dive into pandas

In [23]:
dispatch = pd.read_csv('tuleandispatch.csv')
wra = pd.read_csv('../WRA/combined.csv')

/opt/conda/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (35) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [24]:
dispatch['Camp Name'].unique() # How should we clean the data to reconcile this?

array(['TULE LAKE', 'Tule Lake', 'Gila River', 'Tule 38603-A',
       'Tule Lake  3803-A', 'Tule Lake 2418-B', 'Tule Lake 5413-F',
       ' Tule Lake 1307-A', 'Tule Lake ', 'Santa Fe, Mexico', nan], dtype=object)

In [25]:
# Some Data Cleaning to match with WRA Dataset
# Uppercase the columns of interest
dispatch = dispatch.rename(columns={'Last Name': 'LAST NAME', 'First Name': 'FIRST NAME', 'Camp Name':'RELOCATION PROJECT', 'Destination': 'DESTINATION'})
# Make First name and last name values uppercase
for col_name in ['FIRST NAME', 'LAST NAME']:
    dispatch[col_name] = dispatch[col_name].apply((lambda x: str(x).upper()))

dispatch

,Age,RELOCATION PROJECT,Date of Departure,DESTINATION,FIRST NAME,Gender,LAST NAME,Marital Status,Middle Name,Notes,Occupation,Source
0,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",GEORGE,M,SAKAMOTO,NaN,NaN,NYA WAR PRODUCTION TRAINING CENTER,"MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
1,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",ALBERT,M,OSHITA,NaN,NaN,NYA WAR PRODUCTION TRAINING CENTER,"MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
2,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",THOMAS,M,OSHIKA,NaN,A.,NYA WAR PRODUCTION TRAINING CENTER,"MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
3,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",HENRY,M,SHIHOJIMA,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
4,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",TOM,M,MURAKI,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
5,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",HISASHI,M,KUNAGAI,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
6,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",JACK,M,CKUDA,NaN,V.,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
7,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",SHIG,M,KATO,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
8,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",KUNIO,M,KAWATA,NaN,BILL,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
9,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",BOB,M,OKAMURA,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
10,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",JOE,M,FUJIL,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
11,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",FRANK,M,FUKAMI,NaN,K.,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
12,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",TED,M,OKITA,NaN,T.,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
13,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",JONE,M,KOSHIBA,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
14,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",YAMAMOTO,M,YOSHIYUKI,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
15,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",KAMEO,M,FUJIYE,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
16,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",BEN,M,SUMADA,NaN,T.,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
17,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",KEIRJI,M,YOSHINO,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
18,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",TOKI,M,YOKOTA,NaN,CHARLES,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
19,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",BEN,M,ISALOKE,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
20,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",LESTER,M,KIYONO,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
21,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",FUMIO,M,HAMGAI,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
22,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",GLEN,M,YOSHIZUMI,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
23,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",JAMES,M,TAKEMOTO,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
24,NaN,TULE LAKE,05/26/1943,"SHAKOPEE, MN",ROY,M,YAMAGUCHI,NaN,NaN,"NYA WAR PRODUCTION TRAINING CENTER, project ca...","MACHINERY , SHEET METAL, WELDING, FOUNDRY, PAT...","TULEAN DISPATCH, 5.58"
25,NaN,TULE LAKE,06/08/1943,"CHICAGO, IL",TSUYOSHI,M,NAKMURA,NaN,NaN,"AKA, 'TOOTS'",EDITOR IN CHIEF,"TULEAN DISPATCH, 5.67"
26,NaN,TULE LAKE,06/08/1943,"CHICAGO, IL",BILL,M,OSUGA,NaN,NaN,NaN,RESEARCH EDITOR,"TULEAN DISPATCH, 5.67"
27,NaN,TULE LAKE,05/31/1943,"LOGAN, UT",TOM,M,INUKAI,NaN,NaN,NaN,NaN,"TULEAN DISPATCH, 5.67"
28,NaN,TULE LAKE,05/31/1943,"BOISE, ID",FUMIKO,M,INUKAI,NaN,NaN,NaN,NaN,"TULEAN DISPATCH, 5.67"
29,NaN,TULE LAKE,05/31/1943,"CHICAGO, IL",PENELOPE,F,YABE,NaN,F.,NaN,NaN,"TULEAN DISPATCH, 5.67"
...,...,...,...,...,...,...,...,...,...,...,...,...
429,NaN,Tule Lake,"July 22, 1943","Ontario, Oregon",ALFRED,NaN,NITTA,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
430,NaN,Tule Lake,"July 22, 1943","Ontario, Oregon",HAJIME,NaN,HAMAMOTO,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
431,NaN,Tule Lake,"July 22, 1943","Ontario, Oregon",HARRY,NaN,HIGASHIRO,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
432,NaN,Tule Lake,"July 22, 1943","Ontario, Oregon",ROY,NaN,HIGASHIRO,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
433,NaN,Tule Lake,"July 22, 1943","Chicago, Illinois",GOHEI,NaN,TANAKA,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
434,NaN,Tule Lake,"July 22, 1943","Chicago, Illinois",YASUNO,NaN,TANAKA,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
435,NaN,Tule Lake,"July 22, 1943","Chicago, Illinois",YOSHIKO,NaN,TANAKA,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
436,NaN,Tule Lake,"July 22, 1943","Chicago, Illinois",TARO,NaN,TAKEMURA,NaN,Paul,NaN,NaN,Tulean Dispatch 6.5
437,NaN,Tule Lake,"July 22, 1943","Chicago, Illinois",FRANK,NaN,FUJITA,NaN,T,NaN,NaN,Tulean Dispatch 6.5
438,NaN,Tule Lake,"July 22, 1943","Denver, Colorado",TOSA,NaN,KUMASAKA,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
439,NaN,Tule Lake,"July 22, 1943","Denver, Colorado",YUJI,NaN,KUMASAKA,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
440,NaN,Tule Lake,"July 22, 1943","Denver, Colorado",YUKIO,NaN,KUASAKA,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
441,NaN,Tule Lake,"July 22, 1943","Minneapolis, Minnesota",YOSHIE,NaN,DOI,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
442,NaN,Tule Lake,"July 22, 1943","Minneapolis, Minnesota",TOYOKO,NaN,YOSHIDA,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
443,NaN,Tule Lake,"July 22, 1943","Rockford, Illinois",SUMI,NaN,KOBAYASHI,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
444,NaN,Tule Lake,"July 22, 1943","Rockford, Illinois",AKIRA,NaN,HIRATA,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
445,NaN,Tule Lake,"July 22, 1943","Gering, Nebraska",SADAO,NaN,DAIRIKI,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
446,NaN,Tule Lake,"July 22, 1943","St. Paul, Minnesota",SUMIKO,NaN,YOKOTA,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
447,NaN,Tule Lake,"July 22, 1943","Gary, Indiana",ASAKO,NaN,SHIMA,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
448,NaN,Tule Lake,"July 22, 1943","New York, New York",SAKAUYE,NaN,OKUBO,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
449,NaN,Tule Lake,"July 22, 1943","Lamar, Colorado",NAOKO,NaN,HOSHINO,NaN,NaN,NaN,NaN,Tulean Dispatch 6.5
450,NaN,Tule Lake,9/6/1943,"Colorado Springs, Colorado",YORIJE,NaN,SUGASAWARA,NaN,NaN,NaN,NaN,NaN
451,NaN,Tule Lake,9/6/1943,"Colorado Springs, Colorado",AME,NaN,SUGASAWARA,NaN,NaN,NaN,NaN,NaN
452,NaN,Tule Lake,9/6/1943,"Colorado Springs, Colorado",SAKAE,NaN,SUGASAWARA,NaN,NaN,NaN,NaN,NaN
453,NaN,Tule Lake,9/6/1943,"Colorado Springs, Colorado",SAKAI,NaN,OSHITA,NaN,NaN,NaN,NaN,NaN
454,NaN,Tule Lake,9/6/1943,"Colorado Springs, Colorado",TERUKO,NaN,OSHITA,NaN,NaN,NaN,NaN,NaN
455,70.0,Tule Lake,NaN,(Unknown),MINIOWA,NaN,KUNO,NaN,NaN,NaN,NaN,NaN
456,NaN,Tule Lake,9/24/1943,New York,SHIGAICHI,NaN,KUBO,NaN,NaN,NaN,NaN,NaN
457,NaN,Tule Lake,9/24/1943,New York,"""GORKY""",NaN,KAWASAKI,NaN,NaN,NaN,NaN,NaN
458,NaN,Tule Lake,9/24/1943,New York,WILBUR,NaN,TAKEGUCHI,NaN,NaN,NaN,NaN,NaN

In [26]:
# Merging with WRA
merged = pd.merge(dispatch, wra, on = ['LAST NAME', 'FIRST NAME', 'RELOCATION PROJECT'])
merged

,Age,RELOCATION PROJECT,Date of Departure,DESTINATION,FIRST NAME,Gender,LAST NAME,Marital Status,Middle Name,Notes,...,HIGHEST GRADE COMPLETED OR GRADE ATTENDING,LANGUAGE,RELIGION,PRIMARY OCCUPATION,SECONDARY OCCUPATION,TERTIARY OCCUPATION,POTENTIAL OCCUPATION 1,POTENTIAL OCCUPATION 2,FILE NUMBER,BLANK 1
0,NaN,Tule Lake,NaN,"Rupert, Idaho",TAKEO,NaN,YOSHIHARA,NaN,NaN,Also mentioned in TD 5.4,...,COLLEGE 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,Retail Managers,NaN,NaN,Social and Welfare Workers,"Buyers and Department Heads, Stores",414012,31171
1,NaN,Tule Lake,NaN,"New York, New York",NOBORU,NaN,HONDA,NaN,NaN,Rochdale Institute,...,ELEMENTARY 8 IN U.S.,"JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, RE...",MASKED VALUE,"Salesmen, Insurance","Managers and Officials, N.E.C.",Farm Managers and Foremen,Skilled Carpenters,NaN,414345,51081
2,NaN,Tule Lake,7/5/1943,"Des Plaines, Illinois",NOBORU,NaN,HONDA,NaN,NaN,NaN,...,ELEMENTARY 8 IN U.S.,"JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, RE...",MASKED VALUE,"Salesmen, Insurance","Managers and Officials, N.E.C.",Farm Managers and Foremen,Skilled Carpenters,NaN,414345,51081
3,NaN,Tule Lake,NaN,"New York, New York",FUMI,NaN,SAKAMOTO,NaN,NaN,Rochdale Institute; a letter of hers is convey...,...,COLLEGE 2 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,Retail Managers,Designers,Personal Service Occupations,"Barbers, Beauticians, and Manicurists","Cooks, Domestic",407623,41151
4,NaN,Tule Lake,NaN,"New York, New York",ROBERT,NaN,OTA,NaN,NaN,Rochdale Institute,...,COLLEGE 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,Crop Specialty Farmers,Wholesale Managers,Post Office Clerks,Managerial and Official Occupations,NaN,400632,31171
5,NaN,Tule Lake,NaN,"Ann Arbor, Michigan",GEORGE,NaN,SUMIDA,NaN,NaN,NaN,...,HIGH SCHOOL 1 IN U.S.,"JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, RE...",MASKED VALUE,"Waiters and Waitresses, Except Private Family","Farm Hands, Fruit",NaN,Musicians and Teachers of Music,"Semiprofessional Occupations, N.E.C.",405330,21092
6,NaN,Tule Lake,NaN,"Ann Arbor, Michigan",GEORGE,NaN,SUMIDA,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,Boarding-House and Lodging-House Keepers,Sales Clerks,Ship Stewards,"Skilled Mechanics and Repairmen, Motor Vehicle",Fishermen and Oystermen,408396,51121
7,NaN,Tule Lake,NaN,"Camp Robinson, Arkansas",JOSIE,NaN,YANAGAWA,NaN,S.,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, RE...",MASKED VALUE,Sales Clerks,"Maids, General",NaN,Semiskilled Occupations in Manufacture of Knit...,NaN,412640,31121
8,NaN,Tule Lake,"March 22, 1943","Caldwell, Idaho",MIDORI,NaN,FURUSHIRO,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,Stenographer and Typists,"Cooks, Domestic","Maids and Housemen, Hotels, Restaurants, Etc.",Semiskilled Dressmakers and Seamstresses,Unskilled Occupations in Manufacture of Leathe...,400663,41121
9,NaN,Tule Lake,NaN,"Palatine, Illinois",YURI,NaN,YAMAGIWA,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, RE...",MASKED VALUE,Farm Managers and Foremen,"Semiskilled Chauffeurs and Drivers, Bus, Taxi,...",NaN,Semiskilled Dressmakers and Seamstresses,Social and Welfare Workers,413598,31121
10,NaN,Tule Lake,NaN,"Omaha, Nebraska",JOE,NaN,OKAMOTO,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ & WRITE...",MASKED VALUE,"Semiskilled Chauffeurs and Drivers, Bus, Taxi,...",Semiskilled Apprentices to Other Trades,"Skilled Mechanics and Repairmen, Motor Vehicle",NaN,NaN,405361,41121
11,NaN,Tule Lake,"March 24, 1943","Minneapolis, Minnesota",YURI,NaN,KOBUKATA,NaN,NaN,NaN,...,COLLEGE 1 IN U.S.,"ENGLISH SPEAK, WRITE, READ ONLY",MASKED VALUE,"Maids, General",Undefined Code,NaN,Semiskilled Dressmakers and Seamstresses,Stenographer and Typists,413159,21142
12,NaN,Tule Lake,NaN,Eastern Oregon,PATSY,NaN,OGURA,NaN,NaN,Ogura family,...,NO SCHOOLING OR KINDERGARTEN IN EITHER JAPAN O...,NOT APPLICABLE (11 YRS. AND UNDER),MASKED VALUE,NaN,NaN,NaN,NaN,NaN,403357,13001
13,NaN,Tule Lake,NaN,Eastern Oregon,MINNIE,NaN,OGURA,NaN,NaN,Ogura family,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, RE...",MASKED VALUE,Sales Clerks,"Maids, General","Farm Hands, Vegetable",Musicians and Teachers of Music,Semiskilled Dressmakers and Seamstresses,403351,31122
14,NaN,Tule Lake,NaN,Eastern Oregon,SUMI,NaN,OGURA,NaN,NaN,Ogura family,...,COLLEGE 1 IN U.S.,"JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, RE...",MASKED VALUE,"Farm Hands, Vegetable",Sales Clerks,Skilled Dressmakers and Seamstresses,Musicians and Teachers of Music,Skillled Occupations in Manufacture of Knit Goods,403352,31142
15,NaN,Tule Lake,NaN,Eastern Oregon,ESTHER,NaN,OGURA,NaN,NaN,Ogura family,...,ELEMENTARY 5 IN U.S.,NOT APPLICABLE (11 YRS. AND UNDER),MASKED VALUE,NaN,NaN,NaN,Musicians and Teachers of Music,NaN,403354,11051
16,NaN,Tule Lake,NaN,"Peoria, Illinois",GEORGE,NaN,NOMURA,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ & WRITE...",MASKED VALUE,Truck Farmers,NaN,NaN,"Semiskilled Chauffeurs and Drivers, Bus, Taxi,...",Library Assistants and Attendants,413634,41122
17,NaN,Tule Lake,NaN,"Peoria, Illinois",GEORGE,NaN,NOMURA,NaN,NaN,NaN,...,HIGH SCHOOL 1 IN U.S.,"JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, RE...",MASKED VALUE,"Semiskilled Occupations in Laundering, Cleanin...","Bookkeepers and Cashiers, Except Bank Cashiers","Semiskilled Sawmill Occupations, N.E.C.",Skilled Carpenters,NaN,414573,51092
18,NaN,Tule Lake,NaN,"Peoria, Illinois",MIKE,NaN,HIRAHARA,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"ENGLISH SPEAK, WRITE, READ ONLY",MASKED VALUE,"Semiskilled Chauffeurs and Drivers, Bus, Taxi,...","Skilled Inspectors, Scalers, and Graders, Logs...",NaN,"Athletes, Sports Instructors, and Sports Offic...",Musicians and Teachers of Music,400665,31121
19,NaN,Tule Lake,NaN,"Great Falls, Montana",RAY,NaN,YASUI,NaN,"""Choppie""",Mentioned as a part of 49 farmers,...,COLLEGE 2 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,Fruit Farmers,NaN,NaN,"Inspectors, Public Service, N.E.C.",Fishermen and Oystermen,404625,41152
20,NaN,Tule Lake,NaN,"Great Falls, Montana",JEAN,NaN,AKITA,NaN,NaN,Mentioned as a part of 49 farmers,...,COLLEGE 2 IN U.S.,"ENGLISH SPEAK, WRITE, READ ONLY",MASKED VALUE,Sales Clerks,Managerial and Official Occupations,NaN,"Professional Occupations, N.E.C.",Skilled Dressmakers and Seamstresses,412874,31151
21,NaN,Tule Lake,"May13th,1943","Ft. Leavenworth, Kansas",JOHN,M,KUBO,S,NaN,Millitary Leave,...,HIGH SCHOOL 5 IN JAPAN,"JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, RE...",MASKED VALUE,"Semiskilled Occupations in Laundering, Cleanin...",NaN,Undefined Code,Photographers,NaN,404304,52133
22,NaN,Tule Lake,"Sept. 16, 1942","Hamilton Valley County, Montana",PAUL,M,HAYASHI,S,NaN,Labor leave,...,HIGH SCHOOL 3 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ & WRITE...",MASKED VALUE,"Cooks, Except Private Family",NaN,NaN,"Athletes, Sports Instructors, and Sports Offic...",NaN,412739,31111
23,NaN,Tule Lake,"Sept. 19, 1942","Plaacer County, California",TOM,M,YEGO,S,NaN,Supply Leave,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,Fruit Farmers,"Managers and Officials, N.E.C.",NaN,Fishermen and Oystermen,Hunters and Trappers,402821,51121
24,20.0,Tule Lake,"Sept. 12, 1942","Ogdon, Utah",FRED,M,DODOBARA,S,NaN,Labor leave,...,HIGH SCHOOL 2 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,"Farm Hands, Vegetable",NaN,NaN,"Semiskilled Mechanics and Repairmen, Motor Veh...","Skilled General Woodwork Occupations, N.E.C.",413731,41101
25,NaN,Tule Lake,"Sept. 12, 1942","Ogdon, Utah",MIKE,M,FUJISHIN,S,NaN,Labor leave,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,"Farm Hands, Vegetable",Managerial and Official Occupations,NaN,"Athletes, Sports Instructors, and Sports Offic...",Farm Mechanics,411807,31121
26,NaN,Tule Lake,"Sept. 12, 1942","Ogdon, Utah",KAY,M,FUJISHIN,S,NaN,Labor leave,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,"Farm Hands, Vegetable",Undefined Code,NaN,Skilled Cabinetmakers,Draftsmen,411808,21121
27,NaN,Tule Lake,6/28/1943,"Camp Shelby, Mississippi",TOSHI,NaN,KUGE,NaN,NaN,NaN,...,POST GRADUATE OR COLL. 5 OR MORE IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,Managerial and Official Occupations,"Farm Hands, Vegetable",NaN,Laboratory Technicians and Assistants,Physicians and Surgeons,415052,31181
28,NaN,Tule Lake,6/28/1943,"Minneapolis, Minnesota",FRANK,Male,ISHIKAWA,NaN,NaN,NaN,...,HIGH SCHOOL 1 IN U.S.,"JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, RE...",MASKED VALUE,NaN,NaN,NaN,NaN,NaN,406279,21091
29,NaN,Tule Lake,6/29/1943,"Great Northern Railroad, Spokane, Washington",JUNIUS,NaN,MATSUMOTO,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ & WRITE...",MASKED VALUE,"Farm Hands, Fruit",Semiskilled Occupations in Manufacture of Misc...,"Clerks and Kindred Occupations, N.E.C.","Skilled Pattern and Model Makers, Except Paper",NaN,411499,31121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,NaN,Tule Lake,"July 19, 1943","Widow Rock, Arizona",MASAKO,NaN,ISHIDA,NaN,NaN,NaN,...,POST GRADUATE OR COLL. 5 OR MORE IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,"Teachers, Primary School and Kindergarten",Clerical and Kindred Occupations,NaN,"Clerks, General","Athletes, Sports Instructors, and Sports Offic...",404817,41181
230,NaN,Tule Lake,"July 19, 1943","Cincinnati, Ohio",MASAO,NaN,INADA,NaN,NaN,NaN,...,COLLEGE 2 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ & WRITE...",MASKED VALUE,Sales Clerks,Professional Occupations,NaN,NaN,NaN,402360,31152
231,NaN,Tule Lake,"July 19, 1943","St. Clair, Michigan",TUFFY,NaN,YASUDA,NaN,H,NaN,...,HIGH SCHOOL 2 IN U.S.,"ENGLISH SPEAK, WRITE, READ ONLY",MASKED VALUE,Nursery and Landscaping Laborers,Sales Clerks,NaN,"Semiprofessional Occupations, N.E.C.","Clerks, General Office",404398,41101
232,NaN,Tule Lake,"July 19, 1943","Denver, Colorado",EMIKO,NaN,FUJIMOTO,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, RE...",MASKED VALUE,Hotel and Restaurant Managers,NaN,NaN,Library Assistants and Attendants,"Attendants, Hospitals and Other Institutions, ...",411535,41121
233,NaN,Tule Lake,NaN,"Camp Grant, Illinois",GEORGE,NaN,NISHIKAWA,NaN,NaN,NaN,...,ELEMENTARY 5 IN U.S.,NOT APPLICABLE (11 YRS. AND UNDER),MASKED VALUE,NaN,NaN,NaN,Musicians and Teachers of Music,NaN,406477,11052
234,NaN,Tule Lake,"July 20, 1943","Hunt, Idaho",KANJIRO,NaN,SUZUKI,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN JAPAN,"JAPANESE SPEAK, WRITE, READ ONLY",MASKED VALUE,Nursery Operators and Flower Growers,NaN,NaN,NaN,NaN,415347,82124
235,NaN,Tule Lake,"July 20, 1943","Hunt, Idaho",YUKIKO,NaN,SUZUKI,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"ENGLISH SPEAK, WRITE, READ ONLY",MASKED VALUE,"Clerks, General Office",Semiskilled Dressmakers and Seamstresses,"Maids, General",Semiskilled Occupations in Manufacture of Knit...,Commercial Artists,415346,41122
236,NaN,Tule Lake,"July 21, 1943","Boise, Idaho",GEORGE,NaN,MIYAI,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,Nursery Operators and Flower Growers,Undefined Code,NaN,Photographers,Fishermen and Oystermen,408604,41122
237,NaN,Tule Lake,"July 21, 1943","Boise, Idaho",GEORGE,NaN,MIYAI,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,Undefined Code,Wholesale Managers,NaN,Photographers,Fishermen and Oystermen,408604,41122
238,NaN,Tule Lake,"July 21, 1943","Boise, Idaho",YOSHIMI,NaN,ISHIMOTO,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,Truck Farmers,"Farm Hands, Poultry","Semiskilled Chauffeurs and Drivers, Bus, Taxi,...",Farm Mechanics,Fishermen and Oystermen,405793,41121
239,NaN,Tule Lake,"July 21, 1943","Boise, Idaho",JOE,NaN,TOMITA,NaN,NaN,NaN,...,COLLEGE 1 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,"Farm Hands, Fruit",Semiskilled Occupations in Manufacture of Misc...,NaN,"Athletes, Sports Instructors, and Sports Offic...",NaN,404286,31141
240,NaN,Tule Lake,"July 21, 1943","Boise, Idaho",JOE,NaN,TOMITA,NaN,NaN,NaN,...,ELEMENTARY 1 IN U.S.,NOT APPLICABLE (11 YRS. AND UNDER),MASKED VALUE,NaN,NaN,NaN,NaN,NaN,411766,11011
241,NaN,Tule Lake,"July 22, 1943","Ontario, Oregon",DICKIE,NaN,MORIYASU,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"ENGLISH SPEAK, WRITE, READ ONLY",MASKED VALUE,Skilled Dressmakers and Seamstresses,"Maids, General",Teachers (Secondary School) and Principals,"Artists, Sculptors, and Teachers of Art",NaN,401033,41121
242,NaN,Tule Lake,"July 22, 1943","Ontario, Oregon",FRANCIS,NaN,SUZUKI,NaN,M.,NaN,...,HIGH SCHOOL 3 IN U.S.,"JAPANESE, ENGLISH AND OTHER LANGUAGE SPEAK, RE...",MASKED VALUE,"Farm Hands, Fruit",NaN,NaN,Musicians and Teachers of Music,"Athletes, Sports Instructors, and Sports Offic...",410980,21111
243,NaN,Tule Lake,"July 22, 1943","Ontario, Oregon",ALFRED,NaN,NITTA,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,"Farm Hands, Fruit",Semiskilled Occupations in Manufacture of Misc...,Undefined Code,"Skilled Tinsmiths, Coppersmiths, and Sheet Met...",Musicians and Teachers of Music,404219,21121
244,NaN,Tule Lake,"July 22, 1943","Ontario, Oregon",HAJIME,NaN,HAMAMOTO,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,Nursery Operators and Flower Growers,"Semiskilled Chauffeurs and Drivers, Bus, Taxi,...",Clerical and Kindred Occupations,"Clerks, General Office",NaN,401183,41121
245,NaN,Tule Lake,"July 22, 1943","Chicago, Illinois",GOHEI,NaN,TANAKA,NaN,NaN,NaN,...,ELEMENTARY 8 IN JAPAN,"JAPANESE SPEAK, WRITE, READ ONLY",MASKED VALUE,"Semiskilled Sawmill Occupations, N.E.C.",NaN,NaN,Skilled Carpenters,Library Assistants and Attendants,413167,82084
246,NaN,Tule Lake,"July 22, 1943","Chicago, Illinois",YASUNO,NaN,TANAKA,NaN,NaN,NaN,...,ELEMENTARY 8 IN JAPAN,"JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, RE...",MASKED VALUE,NaN,NaN,NaN,NaN,NaN,413168,72084
247,NaN,Tule Lake,"July 22, 1943","Chicago, Illinois",YOSHIKO,NaN,TANAKA,NaN,NaN,NaN,...,HIGH SCHOOL 3 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,Undefined Code,NaN,NaN,Skilled Dressmakers and Seamstresses,Stenographer and Typists,413169,21111
248,NaN,Tule Lake,"July 22, 1943","Chicago, Illinois",TARO,NaN,TAKEMURA,NaN,Paul,NaN,...,COLLEGE 2 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,Retail Managers,Unskilled Occupations in Canning and Preservin...,Managerial and Official Occupations,Laboratory Technicians and Assistants,Photographers,414524,31152
249,NaN,Tule Lake,"July 22, 1943","Chicago, Illinois",FRANK,NaN,FUJITA,NaN,T,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,"Farm Hands, Fruit",Professional Occupations,NaN,Commercial Artists,Stenographer and Typists,405975,21121
250,NaN,Tule Lake,"July 22, 1943","Chicago, Illinois",FRANK,NaN,FUJITA,NaN,T,NaN,...,ELEMENTARY 8 IN U.S.,"JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, RE...",MASKED VALUE,NaN,NaN,NaN,NaN,NaN,410598,21081
251,NaN,Tule Lake,"July 22, 1943","Denver, Colorado",TOSA,NaN,KUMASAKA,NaN,NaN,NaN,...,HIGH SCHOOL 1 IN JAPAN,"JAPANESE SPEAK, WRITE, READ ONLY",MASKED VALUE,Nursery and Landscaping Laborers,NaN,NaN,Semiskilled Occupations in Manufacture of Knit...,NaN,412466,72094
252,NaN,Tule Lake,"July 22, 1943","Minneapolis, Minnesota",TOYOKO,NaN,YOSHIDA,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,"Maids, General","Farm Hands, Fruit",NaN,Social and Welfare Workers,"Skilled General Woodwork Occupations, N.E.C.",412847,31121
253,NaN,Tule Lake,"July 22, 1943","Rockford, Illinois",AKIRA,NaN,HIRATA,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, RE...",MASKED VALUE,Semiskilled Routemen,Nursery and Landscaping Laborers,NaN,Poultry Farmers,NaN,401023,31122
254,NaN,Tule Lake,"July 22, 1943","Gering, Nebraska",SADAO,NaN,DAIRIKI,NaN,NaN,NaN,...,HIGH SCHOOL 2 IN U.S.,"JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, RE...",MASKED VALUE,NaN,NaN,NaN,NaN,NaN,401675,21102
255,NaN,Tule Lake,"July 22, 1943","St. Paul, Minnesota",SUMIKO,NaN,YOKOTA,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,"Farm Hands, Vegetable",NaN,NaN,Stenographer and Typists,Post Office Clerks,414878,31121
256,NaN,Tule Lake,"July 22, 1943","Gary, Indiana",ASAKO,NaN,SHIMA,NaN,NaN,NaN,...,HIGH SCHOOL 4 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,NaN,NaN,NaN,Semiskilled Dressmakers and Seamstresses,Stenographer and Typists,401803,21122
257,NaN,Tule Lake,"July 22, 1943","Lamar, Colorado",NAOKO,NaN,HOSHINO,NaN,NaN,NaN,...,POST GRADUATE OR COLL. 5 OR MORE IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,Social and Welfare Workers,NaN,NaN,Stenographer and Typists,"Authors, Editors, and Reporters",414617,41181
258,NaN,Tule Lake,9/6/1943,"Colorado Springs, Colorado",TERUKO,NaN,OSHITA,NaN,NaN,NaN,...,COLLEGE 1 IN U.S.,"JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE",MASKED VALUE,"Maids, General",NaN,NaN,Semiskilled Occupations in Manufacture of Knit...,"Artists, Sculptors, and Teachers of Art",406440,31141

In [27]:
def num_occurrences(table, first_name, last_name):
    first_name_s = pd.Series([first_name] * len(table.index))
    last_name_s = pd.Series([last_name]*len(table.index))
    query = table[(table['FIRST NAME'] == first_name_s) &  (table['LAST NAME'] == last_name_s)]
    num_rows = len(query)
    return num_rows

duplicates = set()
for index, row in merged.iterrows():
    first_name, last_name = row['FIRST NAME'], row['LAST NAME']
    n_occurrences = num_occurrences(merged, row['FIRST NAME'], row['LAST NAME'])
    if n_occurrences > 1:
        duplicates.add((first_name, last_name, n_occurrences))
duplicates

{('AIKO', 'YAMAMOTO', 3),
 ('FRANCES', 'MORIOKA', 2),
 ('FRANK', 'FUJITA', 2),
 ('FRANK', 'MATSUMOTO', 4),
 ('FRANK', 'YAMAMOTO', 2),
 ('GEORGE', 'DANZUKA', 4),
 ('GEORGE', 'KATO', 2),
 ('GEORGE', 'KUBO', 2),
 ('GEORGE', 'MIYAI', 2),
 ('GEORGE', 'NOMURA', 2),
 ('GEORGE', 'SUMIDA', 2),
 ('GEORGE', 'TAKAO', 3),
 ('GEORGE', 'TAKETA', 3),
 ('GEORGE', 'YASUI', 2),
 ('HARRY', 'HAMADA', 2),
 ('HIROSHI', 'KANEKO', 2),
 ('HIROSHI', 'NAKAMURA', 3),
 ('JOE', 'TOMITA', 2),
 ('LILY', 'YAMASAKI', 2),
 ('MARY', 'MARUYAMA', 2),
 ('NOBORU', 'HONDA', 2),
 ('PAUL', 'TAKAHASHI', 2),
 ('TAKESHI', 'NAKAMURA', 2),
 ('YOSHIKO', 'SUZUKI', 2),
 ('YOSHIYE', 'FURUTA', 2)}

In [92]:
tulean_dispatch = Table.from_df(merged)
tulean_dispatch

Age  | RELOCATION PROJECT | Date of Departure | DESTINATION             | FIRST NAME | Gender | LAST NAME | Marital Status | Middle Name | Notes                                                      | Occupation            | Source               | Unnamed: 0 | MIDDLE INITIAL | ASSEMBLY CENTER      | LAST PERMANENT ADDRESS                                       | LAST PERMANENT ADDRESS STATE | LAST PERMANENT ADDRESS COUNTY | LAST PERMANENT ADDRESS POPULATION DENSITY                    | BIRTH PLACE OF PARENTS     | FATHERS OCCUPATION IN U.S.          | FATHERS OCCUPATION ABROAD  | TOTAL YEARS OF SCHOOLING IN JAPAN | YEARS OF SCHOOLING IN JAPAN | EDUCATIONAL DEGREES                     | YEAR OF FIRST ARRIVAL IN TERRITORIAL U.S. | TOTAL LENGTH OF TIME IN JAPAN         | NUMBER OF TIMES IN JAPAN    | AGE AT TIME IN JAPAN          | MILITARY AND NAVAL SERVICE, PUBLIC ASSISTANCE AND PENSIONS, PHYSICAL DEFECTS | INDIVIDUAL NUMBER | SEX AND MARITAL STATUS | RACE OF INDIVIDUAL AND SPOUSE        | YEAR OF BIRTH | BIRTH PLACE                 | ALIEN REGISTRATION NUMBER, SOCIAL SECURITY NUMBER AND JAPANESE LANGUAGE SCHOOL | HIGHEST GRADE COMPLETED OR GRADE ATTENDING | LANGUAGE                                                 | RELIGION     | PRIMARY OCCUPATION                            | SECONDARY OCCUPATION                                         | TERTIARY OCCUPATION                           | POTENTIAL OCCUPATION 1                               | POTENTIAL OCCUPATION 2                                       | FILE NUMBER | BLANK 1
nan  | Tule Lake          | nan               | Rupert, Idaho           | TAKEO      | nan    | YOSHIHARA | nan            | nan         | Also mentioned in TD 5.4                                   | nan                   | Tulean Dispatch 5.1b | 957        | nan            | Pinedale             | TACOMA, WASHINGTON                                           | Pacific States - Washington  | PIERCE                        | 25,000 - 999,999                                             | Father=Japan, Mother=Japan | MANAGERIAL & OFFICIAL (EXCEPT FARM) | BLANK, UNKNOWN, NONE, DASH | NONE                              | NONE                        | BACHELORS-SOCIAL SCIENCES & MATHEMATICS | --                                        | NONE                                  | NONE-- NOT ATTENDING SCHOOL | NEVER IN JAPAN                | MASKED VALUE                                                                 | 19414A            | MALE SINGLE            | INDIVIDUAL-JAPANESE; NO SPOUSE       | 18            | Pacific States - Washington | HAS NEITHER A.R. NOR S. S. NUMBER AND HAS ATTENDED JAPANESE LANGUAGE SCHOOL    | COLLEGE 4 IN U.S.                          | JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE         | MASKED VALUE | Retail Managers                               | nan                                                          | nan                                           | Social and Welfare Workers                           | Buyers and Department Heads, Stores                          | 414012      | 31171
nan  | Tule Lake          | nan               | New York, New York      | NOBORU     | nan    | HONDA     | nan            | nan         | Rochdale Institute                                         | Student               | Tulean Dispatch 5.2  | 156        | nan            | None                 | MARYSVILLE,  CALIFORNIA                                      | Pacific States - California  | YUBA                          | 5000 - 9999                                                  | Father=Japan, Mother=Japan | FARM OPERATORS & MANAGERS           | BLANK, UNKNOWN, NONE, DASH | NONE                              | NONE                        | NO DEGREE                               | --                                        | NONE                                  | NONE-- NOT ATTENDING SCHOOL | NEVER IN JAPAN                | MASKED VALUE                                                                 | 38600A            | MALE MARRIED           | INDIVIDUAL-JAPANESE; SPOUSE-JAPANESE | 11            | Pacific States - California | HAS NEITHER A.R. NOR S. S. NUMBER AND HAS ATTENDED JAPANESE LANGUAGE SCHOOL    | ELEMENTARY 8 IN U.S.                       | JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, READ & WRITE | MASKED VALUE | Salesmen, Insurance                           | Managers and Officials, N.E.C.                               | Farm Managers and Foremen                     | Skilled Carpenters                                   | nan                                                          | 414345      | 51081
nan  | Tule Lake          | 7/5/1943          | Des Plaines, Illinois   | NOBORU     | nan    | HONDA     | nan            | nan         | nan                                                        | nan                   | Tulean Dispatch 5.93 | 156        | nan            | None                 | MARYSVILLE,  CALIFORNIA                                      | Pacific States - California  | YUBA                          | 5000 - 9999                                                  | Father=Japan, Mother=Japan | FARM OPERATORS & MANAGERS           | BLANK, UNKNOWN, NONE, DASH | NONE                              | NONE                        | NO DEGREE                               | --                                        | NONE                                  | NONE-- NOT ATTENDING SCHOOL | NEVER IN JAPAN                | MASKED VALUE                                                                 | 38600A            | MALE MARRIED           | INDIVIDUAL-JAPANESE; SPOUSE-JAPANESE | 11            | Pacific States - California | HAS NEITHER A.R. NOR S. S. NUMBER AND HAS ATTENDED JAPANESE LANGUAGE SCHOOL    | ELEMENTARY 8 IN U.S.                       | JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, READ & WRITE | MASKED VALUE | Salesmen, Insurance                           | Managers and Officials, N.E.C.                               | Farm Managers and Foremen                     | Skilled Carpenters                                   | nan                                                          | 414345      | 51081
nan  | Tule Lake          | nan               | New York, New York      | FUMI       | nan    | SAKAMOTO  | nan            | nan         | Rochdale Institute; a letter of hers is conveyed in TD 5.5 | Student               | Tulean Dispatch 5.2  | 701        | nan            | Sacramento (Walerga) | SACRAMENTO, CALIFORNIA                                       | Pacific States - California  | SACRAMENTO                    | 25,000 - 999,999                                             | Father=Japan, Mother=Japan | MANAGERIAL & OFFICIAL (EXCEPT FARM) | BLANK, UNKNOWN, NONE, DASH | NONE                              | NONE                        | NO DEGREE                               | --                                        | NONE                                  | NONE--ATTENDING SCHOOL      | NEVER IN JAPAN                | MASKED VALUE                                                                 | 27323C            | FEMALE MARRIED         | INDIVIDUAL-JAPANESE; SPOUSE-WHITE    | 14            | Pacific States - California | HAS S.S. BUT NOT A.R. NUMBER AND HAS NOT ATTENDED JAPANESE LANGUAGE SCHOOL     | COLLEGE 2 IN U.S.                          | JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE         | MASKED VALUE | Retail Managers                               | Designers                                                    | Personal Service Occupations                  | Barbers, Beauticians, and Manicurists                | Cooks, Domestic                                              | 407623      | 41151
nan  | Tule Lake          | nan               | New York, New York      | ROBERT     | nan    | OTA       | nan            | nan         | Rochdale Institute                                         | Student               | Tulean Dispatch 5.2  | 599        | Y              | None                 | DAVIS OR WINTERS, CALIFORNIA                                 | Pacific States - California  | YOLO                          | Incorporated cities of less than 2500 population All uni ... | Father=Japan, Mother=Japan | FARM OPERATORS & MANAGERS           | BLANK, UNKNOWN, NONE, DASH | NONE                              | NONE                        | BACHELORS-SOCIAL SCIENCES & MATHEMATICS | --                                        | NONE                                  | NONE-- NOT ATTENDING SCHOOL | NEVER IN JAPAN                | MASKED VALUE                                                                 | 37212A            | MALE SINGLE            | INDIVIDUAL-JAPANESE; NO SPOUSE       | 18            | Hawaii - Honolulu County    | HAS S.S. BUT NOT A.R. NUMBER AND HAS NOT ATTENDED JAPANESE LANGUAGE SCHOOL     | COLLEGE 4 IN U.S.                          | JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE         | MASKED VALUE | Crop Specialty Farmers                        | Wholesale Managers                                           | Post Office Clerks                            | Managerial and Official Occupations                  | nan                                                          | 400632      | 31171
nan  | Tule Lake          | nan               | Ann Arbor, Michigan     | GEORGE     | nan    | SUMIDA    | nan            | nan         | nan                                                        | Gas Station Attendant | Tulean Dispatch 5.2  | 766        | H              | Sacramento (Walerga) | SACRAMENTO, CALIFORNIA                                       | Pacific States - California  | SACRAMENTO                    | 25,000 - 999,999                                             | Father=Japan, Mother=Japan | MANAGERIAL & OFFICIAL (EXCEPT FARM) | BLANK, UNKNOWN, NONE, DASH | NONE                              | NONE                        | NO DEGREE                               | nan                                       | 1 YEAR BUT LESS THAN 5 YEARS IN JAPAN | 1 TIME--ATTENDING SCHOOL    | BETWEEN AGES 0-9 & ALSO 10-19 | MASKED VALUE                                                                 | 28188C            | MALE SINGLE            | INDIVIDUAL-JAPANESE; NO SPOUSE       | 25            | Pacific States - California | HAS NEITHER A.R. NOR S. S. NUMBER AND HAS ATTENDED JAPANESE LANGUAGE SCHOOL    | HIGH SCHOOL 1 IN U.S.                      | JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, READ & WRITE | MASKED VALUE | Waiters and Waitresses, Except Private Family | Farm Hands, Fruit                                            | nan                                           | Musicians and Teachers of Music                      | Semiprofessional Occupations, N.E.C.                         | 405330      | 21092
nan  | Tule Lake          | nan               | Ann Arbor, Michigan     | GEORGE     | nan    | SUMIDA    | nan            | nan         | nan                                                        | Gas Station Attendant | Tulean Dispatch 5.2  | 759        | M              | Sacramento (Walerga) | SACRAMENTO, CALIFORNIA                                       | Pacific States - California  | SACRAMENTO                    | 25,000 - 999,999                                             | Father=Japan, Mother=Japan | FARM OPERATORS & MANAGERS           | FARM OPERATORS & MANAGERS  | NONE                              | NONE                        | NO DEGREE                               | --                                        | NONE                                  | NONE-- NOT ATTENDING SCHOOL | NEVER IN JAPAN                | MASKED VALUE                                                                 | 28335G            | MALE MARRIED           | INDIVIDUAL-JAPANESE; SPOUSE-WHITE    | 12            | Pacific States - California | HAS S.S. BUT NOT A.R. NUMBER AND HAS NOT ATTENDED JAPANESE LANGUAGE SCHOOL     | HIGH SCHOOL 4 IN U.S.                      | JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE         | MASKED VALUE | Boarding-House and Lodging-House Keepers      | Sales Clerks                                                 | Ship Stewards                                 | Skilled Mechanics and Repairmen, Motor Vehicle       | Fishermen and Oystermen                                      | 408396      | 51121
nan  | Tule Lake          | nan               | Camp Robinson, Arkansas | JOSIE      | nan    | YANAGAWA  | nan            | S.          | nan                                                        | nan                   | Tulean Dispatch 5.2  | 926        | S              | Pinedale             | SEATTLE, WASHINGTON                                          | Pacific States - Washington  | KING                          | 25,000 - 999,999                                             | Father=Japan, Mother=Japan | FARM OPERATORS & MANAGERS           | BLANK, UNKNOWN, NONE, DASH | NONE                              | NONE                        | NO DEGREE                               | --                                        | NONE                                  | NONE-- NOT ATTENDING SCHOOL | NEVER IN JAPAN                | MASKED VALUE                                                                 | 17060D            | FEMALE SINGLE          | INDIVIDUAL-JAPANESE; NO SPOUSE       | 20            | Pacific States - Washington | HAS S.S. BUT NOT A.R. NUMBER AND HAS ATTENDED JAPANESE LANGUAGE SCHOOL         | HIGH SCHOOL 4 IN U.S.                      | JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, READ & WRITE | MASKED VALUE | Sales Clerks                                  | Maids, General                                               | nan                                           | Semiskilled Occupations in Manufacture of Knit Goods | nan                                                          | 412640      | 31121
nan  | Tule Lake          | March 22, 1943    | Caldwell, Idaho         | MIDORI     | nan    | FURUSHIRO | nan            | nan         | nan                                                        | nan                   | Tulean Dispatch 5.2  | 96         | nan            | None                 | DAVIS OR WINTERS, CALIFORNIA                                 | Pacific States - California  | YOLO                          | Incorporated cities of less than 2500 population All uni ... | Father=Japan, Mother=Japan | PROFESSIONAL & SEMI-PROFESSIONAL    | BLANK, UNKNOWN, NONE, DASH | NONE                              | NONE                        | NO DEGREE                               | --                                        | NONE                                  | NONE-- NOT ATTENDING SCHOOL | NEVER IN JAPAN                | MASKED VALUE                                                                 | 37253B            | FEMALE MARRIED         | INDIVIDUAL-JAPANESE; SPOUSE-JAPANESE | 16            | Mountain States - Colorado  | HAS S.S. BUT NOT A.R. NUMBER AND HAS NOT ATTENDED JAPANESE LANGUAGE SCHOOL     | HIGH SCHOOL 4 IN U.S.                      | JAPANESE SPEAKING; ENGLISH SPEAK, READ AND WRITE         | MASKED VALUE | Stenographer and Typists                      | Cooks, Domestic                                              | Maids and Housemen, Hotels, Restaurants, Etc. | Semiskilled Dressmakers and Seamstresses             | Unskilled Occupations in Manufacture of Leather Products ... | 400663      | 41121
nan  | Tule Lake          | nan               | Palatine, Illinois      | YURI       | nan    | YAMAGIWA  | nan            | nan         | nan                                                        | nan                   | Tulean Dispatch 5.2  | 916        | nan            | Pinedale             | BOTHELL, REDMOND, KIRKLAND, DUVALL, ISSAQUAH, NORTH BEND ... | Pacific States - Washington  | KING                          | Incorporated cities of less than 2500 population All uni ... | Father=Japan, Mother=Japan | FARM OPERATORS & MANAGERS           | BLANK, UNKNOWN, NONE, DASH | NONE                              | NONE                        | NO DEGREE                               | --                                        | NONE                                  | NONE-- NOT ATTENDING SCHOOL | NEVER IN JAPAN                | MASKED VALUE                                                                 | 19948A            | FEMALE SINGLE          | INDIVIDUAL-JAPANESE; NO SPOUSE       | 21            | Pacific States - Washington | HAS NEITHER A.R. NOR S. S. NUMBER AND HAS ATTENDED JAPANESE LANGUAGE SCHOOL    | HIGH SCHOOL 4 IN U.S.                      | JAPANESE SPEAK, WRITE, READ; ENGLISH SPEAK, READ & WRITE | MASKED VALUE | Farm Managers and Foremen                     | Semiskilled Chauffeurs and Drivers, Bus, Taxi, Truck, an ... | nan                                           | Semiskilled Dressmakers and Seamstresses             | Social and Welfare Workers                                   | 413598      | 31121
... (249 rows omitted)

In [98]:
# Grouping by first
get_first = lambda x: x[0]
tulean_dispatch= tulean_dispatch.group('FIRST NAME', collect = get_first).group('LAST NAME', collect = get_first)
# Get Columns of Interest
tulean_dispatch = tulean_dispatch.select(['FIRST NAME', 'LAST NAME', 'RELOCATION PROJECT', 'LAST PERMANENT ADDRESS STATE', 'LAST PERMANENT ADDRESS COUNTY', 'ASSEMBLY CENTER', 'DESTINATION'])

In [105]:
coords = Table.read_table('tuleandispatch_coordinates.csv')
# Group locations
coords = coords.group('Location', collect = lambda x: x[0])
# Join Coordinates and locations
def process_coords(coords):
    return list([float(coord) for coord in coords.split(',')])
locations = ['RELOCATION PROJECT', 'DESTINATION']
for name in locations:
    tulean_dispatch = tulean_dispatch.join(name, coords, 'Location')
    tulean_dispatch[name + ' COORDS'] = tulean_dispatch.apply(process_coords, 'Lat,Long')
    tulean_dispatch = tulean_dispatch.drop(['Lat,Long', 'Notes'])

In [106]:
tulean_dispatch

DESTINATION                     | RELOCATION PROJECT | FIRST NAME | LAST NAME | LAST PERMANENT ADDRESS STATE | LAST PERMANENT ADDRESS COUNTY | ASSEMBLY CENTER      | RELOCATION PROJECT COORDS | DESTINATION COORDS
Ann Arbor, Michigan             | Tule Lake          | GEORGE     | SUMIDA    | Pacific States - California  | SACRAMENTO                    | Sacramento (Walerga) | [  41.9688 -121.5681]     | [42.281389, -83.748333]
Baldwin, Kansas                 | Tule Lake          | KATE       | KYONO     | Pacific States - Oregon      | MARION                        | None                 | [  41.9688 -121.5681]     | [38.7775, -95.1875]
Boise, Idaho                    | Tule Lake          | JANE       | HAMADA    | Pacific States - California  | SANTA CRUZ                    | Marysville (Arboga)  | [  41.9688 -121.5681]     | [43.6187, -116.2146]
Boise, Idaho                    | Tule Lake          | YOSHIMI    | ISHIMOTO  | Pacific States - California  | SACRAMENTO                    | Sacramento (Walerga) | [  41.9688 -121.5681]     | [43.6187, -116.2146]
Boise, Idaho                    | Tule Lake          | ELAINE     | TSUMURA   | nan                          | nan                           | None                 | [  41.9688 -121.5681]     | [43.6187, -116.2146]
CLEVELAND, OHIO                 | Tule Lake          | KIKUJI     | RYUGO     | Pacific States - California  | SACRAMENTO                    | Sacramento (Walerga) | [  41.9688 -121.5681]     | [41.505493, -81.68129]
Caldwell, Idaho                 | Tule Lake          | MIDORI     | FURUSHIRO | Pacific States - California  | YOLO                          | None                 | [  41.9688 -121.5681]     | [43.658333, -116.680278]
Camp Granada - Amacha, Colorado | Tule Lake          | FUSAKO     | TEKAWA    | Pacific States - California  | YUBA                          | None                 | [  41.9688 -121.5681]     | [38.064722, -102.311111]
Camp Robinson, Arkansas         | Tule Lake          | JOSIE      | YANAGAWA  | Pacific States - Washington  | KING                          | Pinedale             | [  41.9688 -121.5681]     | [34.85, -92.300278]
Camp Savage, Minnesota          | Tule Lake          | SARA       | TANIGAWA  | Pacific States - California  | PLACER                        | Sacramento (Walerga) | [  41.9688 -121.5681]     | [44.783333, -93.333333]
... (102 rows omitted)

In [107]:
def get_from_to_coords(table, from_location, to_location):
    result = table.select([from_location + ' COORDS', to_location + ' COORDS'])
    result.relabel(from_location + ' COORDS', 'from')
    result.relabel(to_location + ' COORDS', 'to')
    return result
relocation_to_destination = get_from_to_coords(tulean_dispatch, 'RELOCATION PROJECT', 'DESTINATION')
relocation_to_destination

['RELOCATION PROJECT COORDS', 'DESTINATION COORDS']

In [109]:
relocation_to_destination['from'][0]

array([  41.9688, -121.5681])

In [137]:
import folium
from IPython.display import HTML

def display(m, height=500):
    """Takes a folium instance and embed HTML."""
    m._build_map()
    srcdoc = m.HTML.replace('"', '&quot;')
    embed = HTML('<iframe srcdoc="{0}" '
                 'style="width: 100%; height: {1}px; '
                 'border: none"></iframe>'.format(srcdoc, height))
    return embed


m = folium.Map(location=[39.828175, -98.5795], zoom_start=4, tiles='Stamen Terrain')
# Create the map with the appoximate location of San Andreas Fault
for from_to in relocation_to_destination.rows:
    #from_to = folium.PolyLine(locations=list(row),weight=2,color = 'red')
    m.line(from_to, line_weight=3, line_color = '#a3c6ff', line_opacity = 0.7)
display(m)

https://github.com/jwass/folium/commit/865eda47ddcec937ab22fa39503cebb11a754a69#commitcomment-6469995

In [97]:
process_coords(coords.where('Location', 'Tule Lake')['Lat,Long'][0])

[41.9688, -121.5681]

In [126]:
dir(folium.Map)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_auto_bounds',
 '_build_map',
 '_popup_render',
 '_repr_html_',
 'add_layers_to_map',
 'add_tile_layer',
 'add_wms_layer',
 'circle_marker',
 'click_for_marker',
 'create_map',
 'display',
 'fit_bounds',
 'geo_json',
 'lat_lng_popover',
 'line',
 'multiline',
 'polygon_marker',
 'simple_marker']